### ISSUE TITLE
bug: image quality loss after conversion

### ISSUE THREAD

**Issue by lanternx** [andreped/vsi2tif#18]
I performed command line 'vsi2tif -i a.vsi -o b.tif -b bfconvert', and got a smaller 'tif' with lower quality. 
I wonder if there is a way to convert 'vsi' to 'tif' losslessly.

**Comment by andreped** [comment]
@lanternx Hmm, I am not sure.

vsi2tif first converts the Olympus image to uncompressed BigTIFF using **bfconvert from Bioformats**. In the next step, we try to construct the tiled, pyramidal image using **vips tiffsave**. In the first step we uncompress the image and in the second step by default we use JSON compression with 85% quality.

These two steps do not really communicate with each other, so the second step does not know anything about how the original Olympus image was compressed or stored.

Perhaps there is a way to create the new image with the same compression that was used before. I have not explored that option (yet). Or perhaps there is a way to do this in a single step which preserves the original compression (lossless) - not sure.

Maybe you could check the documentations of vips, which is what we use to create the image pyramid (for docs, perhaps see [here](https://libvips.github.io/pyvips/vimage.html#pyvips.Image.tiffsave) and [here](https://www.rubydoc.info/gems/ruby-vips/Vips/Image:tiffsave#:~:text=Defined%20in:%20lib/vips/methods.rb.%20permalink%20#%20tiffsave%20(filename,%20**opts)%20%E2%87%92%20nil)). Please also refer to the Bioformats bfconvert CLI (see [here](https://docs.openmicroscopy.org/bio-formats/5.7.1/users/comlinetools/conversion.html)).

I can have a look after work today, but if you find anything, please let me know, @lanternx :]

**Comment by andreped** [comment]
@dbouget You have any ideas on how we could do this? Perhaps we should look at the legacy, private OME-TIFF converter on how we handled this.

Although I am quite certain we still created an uncompressed raw image in the first step before creating the compressed pyramidal image - so we likely had the same issue.

**Comment by andreped** [comment]
@lanternx After thinking on this for a bit, I don't think it is possible to do the following operation uncompress-decompress lossless even if you use the exact same algorithm used for the original image.

I think for now, I would recommend trying a different quality value. I recall testing `87%` instead of `85%` with great success. Perhaps you could give that a go and report back? See [here](https://github.com/andreped/vsi2tif?tab=readme-ov-file#usage) for more information on usage. Below is an example:
```
vsi2tif -i /path/to/orig.vsi -o /path/to/converted.tiff -b /path/to/bfconvert -j "jpeg" -q 0.87
```

---
So if we want to do this truly lossless, we need a completely different approach for converting the images. This would likely require a different tool than `bfconvert` - perhaps implementing a custom converter entirely from scratch. This effort is something I don't have time to do, unfortunately, as it would require a lot of work and this I primarily do in my sparetime.

**Comment by lanternx** [comment]
@andreped I tried the parameter "0.87" and got a little bit increase in the image quality. I'll use this to further train models. 
Thank you.

**Comment by andreped** [comment]
@lanternx Could be that you could try further increasing the quality. Perhaps try 0.88 or an even higher value. Does the final image size result in a similar size as the original image? I believe that would be the goal.

**Comment by andreped** [comment]
@lanternx As the original problem seems to be resolved. I will close this issue. Feel free to re-open another one, if you find new bugs or features you want added :]
