### ISSUE TITLE
Colors seem off after conversion

### ISSUE THREAD

**Issue by bwentzloff** [andreped/vsi2tif#4]
When I convert a VSI using this script, there is way more blue in the resulting image than when I convert using CellSens. I have been playing around with the bfconvert settings, but nothing seems to change it at all. Have you seen any problems like this?

**Comment by andreped** [comment]
Have not observed the same. Can you send a screenshot of the before and after conversion?

I'm currently on vacation, and therefore might be unable to assist any further right now, but perhaps you could try the original script, which used two CLIs instead of a mix between a CLI and a pythonic solution:
https://github.com/andreped/vsi2tif/blob/fd7cfafe82b24a989e9f1b79e324ae60f7e84a9b/vsi2tif.py

Just need to update the paths to match your setup. Conversion should really be quite easy.

If you are still struggling to convert, and find no other alternative, pyFAST supports reading the CellSens VSI format. Example of how to use pyFAST for reading patches from WSIs can be seen here:
https://github.com/smistad/FAST/blob/master/source/FAST/Examples/Python/generate_tissue_patches_from_wsi.py

**Comment by bwentzloff** [comment]
There must have been something weird about the VSIs I was originally attempting to convert. I have had success with other VSIs since. At some point I'll try to investigate further about what setting may have caused that but for now all seems to be working as expected. Thanks for this handy tool!

**Comment by andreped** [comment]
OK, great! Strange that you had issues only with one WSI, but as long as it suits your needs I guess it is fine for now. Let me know if you get any more problems on new images, and we could try to debug it.

Always happy to help :]

**Comment by andreped** [comment]
As the tool seem to be working for you, I will close this for now.

If you experience any issues and can provide screenshots showing the before/after images, I can reopen and we can debug this further, but ideally you would also provide an image I could test to reproduce the error and use to potentially solve the issue.
